### ISSUE TITLE
George can add MUI to Ghidra

### ISSUE THREAD

**Issue by sschriner** [trailofbits/ManticoreUI#32]
### What:

Ghidra is written in Java, which presents a challenge for interaction with Manticore written in Python.

We want to first develop a prototype Ghidra plugin that will appear similarly to the Binary Ninja plugin but written for Ghidra in Java.

This will initially exist as a separate repository because it's a prototype. The features will be very light in terms of MUI capabilities, but will at least support starting Manticore with an arbitrary command line argument list from a Ghidra UI component and then piping Manticore's output to a Ghidra UI component. The user will also be able to stop Manticore.

### Acceptance Criteria:

- [x] A Ghidra plugin repository that has basic documentation for building, running, and deploying MUI-Ghidra
- [x] A plugin menu item to open a window for Manticore initialization
- [x] A window popup to write a CLI argument list for Manticore, pre-populated with the path to the currently opened binary, and also has a "Run" button to start execution
- [x] A logging UI screen that pops into existence after hitting "Run" to show Manticore's output
- [x] A stop button in the logging UI screen that will kill the Manticore process
- [x] George is able to complete the above on his Linux machine (native binaries will need to appear at `os/linux_x86_64` )
- **N/A** ~George is able to complete the above on his Mac machine (native binaries will need to appear at `os/mac_x86_64`)~ _Removing this because supporting the running of Linux binaries on Mac detracts from other important goals. Manticore also can't process Mach-o binaries._

[Shiv](https://shiv.readthedocs.io/en/latest/) might be useful for packaging Manticore into an executable.

From #1

**Comment by kokrui** [comment]
closed by https://github.com/trailofbits/MUI-Ghidra/pull/1
