### ISSUE TITLE
Improve logging of Manticore Run state

### ISSUE THREAD

**Issue by lordidiot** [trailofbits/ManticoreUI#39]
Currently when we use the `Solve with manticore` functionality, manticore will start and the background process indicator will show in the bottom right corner, but this is not very obvious when looking at the logs. Similarly, when manticore exits without hitting any find/avoids, it will just quietly stop the worker threads with not much information to the user.

I think it would be beneficial to add the following logging messages:
1. Start of manticore solve
2. End of manticore solve
   - After hitting a find
   - **WITHOUT** hitting a find

I think timestamps could be useful as well (so that we can track how long manticore has been running), but I'm not sure if we want that.

**Comment by ekilmer** [comment]
> I think timestamps could be useful as well (so that we can track how long manticore has been running), but I'm not sure if we want that.

Timestamps sound like a good idea to me!

**Comment by lordidiot** [comment]
closed in https://github.com/trailofbits/ManticoreUI/pull/41
