### ISSUE TITLE
Ghidra custom hook behaviour mismatch

### ISSUE THREAD

**Issue by lordidiot** [trailofbits/ManticoreUI#81]
There is a mismatch between the behaviour of the Ghidra and Binary Ninja plug-ins.

**Ghidra**
If a custom hook exists at address A, creating a custom hook at A **again** creates a new custom hook at the same address.

**Binary Ninja**
If a custom hook exists at address A, trying to create a custom hook at A **again** will edit the old custom hook.

I think the way binary ninja does it is more convenient for the user as they can edit their past mistakes/update their custom hooks. However, it may be useful to also support adding multiple hooks on the same address to partition out functionally different custom hooks that are needed on the same address.

**Comment by kokrui** [comment]
Superseded by #83
